### ISSUE TITLE
Issue with Python3.2 handling of byte arrays

### ISSUE THREAD

**Issue by dhhagan** [DancingQuanta/pyusbiss#1]
- pyusbiss version: 0.1.0
- Python version: 3.2.3
- Operating System: Raspbian
### Description

Using Python3.2, upon initialization of the `opc.OPCN2` class, an error is thrown due to the way byte arrays are handled in python3 vs python2.
### What I Did

```
TypeError: 'int' does not support the buffer interface

decoded = [struct.unpack('B', response[i + 1])[0] for i in range(0, len(data))]
```

This is a fairly straightforward fix..I think the bytes need to be sent as arrays...I'll take a look at it tomorrow morning.

NOTE: I was able to get this up and running with Python2.7 without any issues.

**Comment by DancingQuanta** [comment]
I haven't had time to test on python 3.x and my placement is finished so I
do not have the hardware.
If you can make this compatible with 3.x that would be great!

**Comment by dhhagan** [comment]
Awesome. I sent a PR a few hours ago that includes the patch!
