### ISSUE TITLE
Proper Releases

### ISSUE THREAD

**Issue by dhhagan** [DancingQuanta/pyusbiss#6]
* pyusbiss version: all
* Python version: all
* Operating System: all

It may be a good idea to start "releasing" the library in a more structured way; I noticed that there is currently no way for me to easily download the previous version of the code, which means I have to always keep the py-opc library up to date with what is happening here. While I try to do that as best as possible, it would be nice to be able to point people to specific releases!

It's as easy as just going to the "Releases" tab and using the GUI to make one. Does that seem reasonable?

**Comment by DancingQuanta** [comment]
Yes, I am in process of doing releases. I am learning how to do this. It
will takes some time for me.
When I have sorted this out I will do a pull request on your py-opc to stay
current with this library.
Sorry about the mess.

**Comment by DancingQuanta** [comment]
In the meantime, could you test my library branch classes2'with opc please?

On 5 Mar 2018 4:53 p.m., "Andrew Tolmie" <andytheseeker@gmail.com> wrote:

Yes, I am in process of doing releases. I am learning how to do this. It
will takes some time for me.
When I have sorted this out I will do a pull request on your py-opc to stay
current with this library.
Sorry about the mess.

**Comment by dhhagan** [comment]
@DancingQuanta No worries! If you need any help, let me know and I'll do my best!

**Comment by DancingQuanta** [comment]
Released 0.2.0 to pypi. I made a PR against your py-opc to update the instructions on using this library.
